# Generated by Django 6.0.3 on 2026-06-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0006_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='posts.post'),
        ),
    ]
