# Generated by Django 6.0.3 on 2026-03-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_likes_post_badge_post_likes_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
